version: '3.8'

services:

  db:
    container_name: nestjs_mysql
    image: mysql
    command: [ mysqld, --default-authentication-plugin=mysql_native_password, --character-set-server=utf8, --collation-server=utf8_polish_ci, --innodb_monitor_enable=all, --max-connections=1001 ]
    environment:
      - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql

  redis:
    container_name: nestjs_redis
    image: redis:7-bullseye
    ports:
      - ${REDIS_PORT}
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: nestjs_redis
      REDIS_HOST: nestjs_redis
      REDIS_PORT: redis:6379
    ports:
      - 8081:8081

  backend:
    container_name: nestjs_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    volumes:
      - ${PROJECT_ROOT}
    command: npm run start:dev
